stages:
  - build
  - push

variables:
  IMAGE_NAME: registry.gitlab.com/529-stu/vmarble-warehouse-management-service

.go_base:
  image: golang:1.25-alpine
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
    GOCACHE: $CI_PROJECT_DIR/.go/build-cache
  cache:
    key:
      files:
        - go.sum
    paths:
      - .go/pkg/mod/
      - .go/build-cache/

go-build:
  extends: .go_base
  stage: build
  rules:
    - if: >
        $CI_PIPELINE_SOURCE == "merge_request_event" &&
        $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
  script:
    - go build ./...

docker-push:
  stage: push
  image: docker:26
  services:
    - name: docker:26-dind
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_PIPELINE_SOURCE == "push"'
  script:
    - docker build
        -t "${IMAGE_NAME}:sha-${CI_COMMIT_SHORT_SHA}"
        -t "${IMAGE_NAME}:stg-latest"
        .
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push "${IMAGE_NAME}:sha-${CI_COMMIT_SHORT_SHA}"
    - docker push "${IMAGE_NAME}:stg-latest"
    - apk add --no-cache curl
    - curl -sS -f -X POST "$DOKPLOY_BE_WEBHOOK_URL"
