-- +goose Up
-- Finished-Goods Pool (#291). Each row = one physical FG with a unique barcode.
-- Auto-created when a WorkOrder advances to COMPLETED — qty rows per WO. Rows
-- start AVAILABLE, flip to RESERVED when a delivery container_line is added,
-- LOADED when the container is sealed, DEFECT when packing reports an issue.
-- DISPOSED is terminal (DISCARD resolution or scrapped after RETURN_NCC).
CREATE TABLE fg_pool (
    id                   UUID        PRIMARY KEY,
    work_order_id        UUID        NOT NULL REFERENCES work_orders(id),
    sku_id               UUID        NOT NULL REFERENCES skus(id),
    -- One barcode per FG (1:1). The barcode is generated by the barcode module
    -- as part of the WO COMPLETED hook, so it always exists when this row does.
    barcode_id           UUID        UNIQUE NOT NULL REFERENCES barcodes(id),
    -- Soft allocation: copied from work_orders.sales_order_line_id at create
    -- time. Nullable for legacy PO-rooted WOs that never touched a sales order.
    -- Re-allocation across SOs (#315) will rewrite this column.
    sales_order_line_id  UUID        REFERENCES sales_order_lines(id),
    status               TEXT        NOT NULL DEFAULT 'AVAILABLE',
    -- container_line_id is set when status becomes RESERVED/LOADED and cleared
    -- when the line is removed (status flips back to AVAILABLE).
    container_line_id    UUID        REFERENCES container_lines(id),
    qc_passed_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    qc_passed_by         UUID        NOT NULL REFERENCES users(id),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_fg_status CHECK (status IN ('AVAILABLE','RESERVED','LOADED','DEFECT','DISPOSED')),
    -- RESERVED and LOADED rows MUST point at a container_line; AVAILABLE / DEFECT
    -- / DISPOSED rows MUST NOT. Enforced at the DB so a future bug that flips
    -- status without updating container_line_id (or vice versa) cannot persist.
    CONSTRAINT chk_fg_reserved_has_line CHECK (
        (status IN ('RESERVED','LOADED') AND container_line_id IS NOT NULL)
        OR
        (status NOT IN ('RESERVED','LOADED') AND container_line_id IS NULL)
    )
);

-- Hot path: "next AVAILABLE FG matching this SKU" — packing scan + delivery
-- AddLine reservation hook both filter on (status, sku_id).
CREATE INDEX idx_fg_pool_status_sku ON fg_pool (status, sku_id);
-- Partial index for the soft-allocation lookups; sales_order_line_id is null
-- on legacy PO-rooted WOs so the partial index keeps the planner queries small.
CREATE INDEX idx_fg_pool_so_line ON fg_pool (sales_order_line_id)
    WHERE sales_order_line_id IS NOT NULL;
CREATE INDEX idx_fg_pool_wo ON fg_pool (work_order_id);
-- Reverse lookup from container_line → FG used by delivery.DeleteLine release
-- hook and delivery.Seal MarkLoaded hook.
CREATE INDEX idx_fg_pool_container_line ON fg_pool (container_line_id)
    WHERE container_line_id IS NOT NULL;

-- 1:1 with fg_pool — UNIQUE (fg_pool_id) enforces "one defect record per FG".
-- A row landing here means the FG was already flipped to DEFECT in fg_pool;
-- the two writes happen atomically inside ReportDefect's transaction.
CREATE TABLE fg_defect (
    id            UUID        PRIMARY KEY,
    fg_pool_id    UUID        UNIQUE NOT NULL REFERENCES fg_pool(id),
    reason        TEXT        NOT NULL,
    detail        TEXT,
    -- photo_urls is a free-form array — for v1 the kiosk uploads to its own
    -- store and passes URLs back. A dedicated upload endpoint will land
    -- separately; this column accepts that future flow without migration.
    photo_urls    TEXT[],
    detected_by   UUID        NOT NULL REFERENCES users(id),
    detected_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Resolution + audit columns are populated by ResolveDefect. v1 only
    -- records the marker; v3 (#291 follow-up) wires REWORK to a supplemental
    -- WO and RETURN_NCC to material_rejection.
    resolution    TEXT,
    resolved_by   UUID        REFERENCES users(id),
    resolved_at   TIMESTAMPTZ,
    note          TEXT,
    CONSTRAINT chk_fg_defect_reason CHECK (
        reason IN ('BROKEN','WRONG_SIZE','MISSING_ACCESSORY','SCRATCHED','OTHER')
    ),
    CONSTRAINT chk_fg_defect_resolution CHECK (
        resolution IS NULL OR resolution IN ('DISCARD','REWORK','RETURN_NCC')
    ),
    CONSTRAINT chk_fg_defect_resolution_audit CHECK (
        (resolution IS NULL AND resolved_by IS NULL AND resolved_at IS NULL)
        OR
        (resolution IS NOT NULL AND resolved_by IS NOT NULL AND resolved_at IS NOT NULL)
    )
);

CREATE INDEX idx_fg_defect_unresolved ON fg_defect (detected_at DESC)
    WHERE resolution IS NULL;

-- +goose Down
DROP INDEX IF EXISTS idx_fg_defect_unresolved;
DROP TABLE IF EXISTS fg_defect;
DROP INDEX IF EXISTS idx_fg_pool_container_line;
DROP INDEX IF EXISTS idx_fg_pool_wo;
DROP INDEX IF EXISTS idx_fg_pool_so_line;
DROP INDEX IF EXISTS idx_fg_pool_status_sku;
DROP TABLE IF EXISTS fg_pool;
