-- +goose Up
-- Add human-readable codes to work_orders and barcodes so fg_pool display
-- doesn't expose raw UUIDs to warehouse staff. Codes are auto-generated by
-- DB sequences; existing rows are backfilled before the UNIQUE constraint lands.
CREATE SEQUENCE wo_code_seq   START 1;
CREATE SEQUENCE barcode_code_seq START 1;

-- Add columns nullable first so the per-row backfill UPDATE can run
-- before the UNIQUE index is built (ADD COLUMN ... DEFAULT with nextval
-- would call nextval once and assign the same value to all rows).
ALTER TABLE work_orders ADD COLUMN work_order_code TEXT;
ALTER TABLE barcodes    ADD COLUMN barcode_code    TEXT;

-- Backfill: nextval() called once per row → all values unique.
UPDATE work_orders
   SET work_order_code = 'WO-' || to_char(created_at, 'YYYYMMDD') || '-' || lpad(nextval('wo_code_seq')::text, 4, '0');

UPDATE barcodes
   SET barcode_code = 'FG-' || lpad(nextval('barcode_code_seq')::text, 6, '0');

-- Safe to add UNIQUE and DEFAULT now that every row has a value.
ALTER TABLE work_orders
    ALTER COLUMN work_order_code SET DEFAULT
        'WO-' || to_char(now(), 'YYYYMMDD') || '-' || lpad(nextval('wo_code_seq')::text, 4, '0'),
    ADD CONSTRAINT uq_work_orders_code UNIQUE (work_order_code);

ALTER TABLE barcodes
    ALTER COLUMN barcode_code SET DEFAULT 'FG-' || lpad(nextval('barcode_code_seq')::text, 6, '0'),
    ADD CONSTRAINT uq_barcodes_code UNIQUE (barcode_code);

-- +goose Down
ALTER TABLE barcodes    DROP CONSTRAINT IF EXISTS uq_barcodes_code,
                        DROP COLUMN    IF EXISTS barcode_code;
ALTER TABLE work_orders DROP CONSTRAINT IF EXISTS uq_work_orders_code,
                        DROP COLUMN    IF EXISTS work_order_code;
DROP SEQUENCE IF EXISTS barcode_code_seq;
DROP SEQUENCE IF EXISTS wo_code_seq;
